CREATE TABLE IF NOT EXISTS BPM_PROCESSDEF (
    PROCESSDEF_ID VARCHAR(64) PRIMARY KEY,
    DEFNAME VARCHAR(255),
    DESCRIPTION VARCHAR(1024),
    CLASSIFICATION VARCHAR(64),
    SYSTEMCODE VARCHAR(32),
    ACCESSLEVEL VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS BPM_PROCESSDEF_VERSION (
    PROCESSDEF_VERSION_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEF_ID VARCHAR(64),
    VERSION INT,
    PUBLICATIONSTATUS VARCHAR(32),
    ACTIVETIME BIGINT,
    FREEZETIME BIGINT,
    DESCRIPTION VARCHAR(1024),
    CREATORID VARCHAR(64),
    CREATORNAME VARCHAR(128),
    CREATED BIGINT,
    MODIFIERID VARCHAR(64),
    MODIFIERNAME VARCHAR(128),
    MODIFYTIME BIGINT,
    LIMITTIME INT DEFAULT 0,
    DURATIONUNIT VARCHAR(16),
    FOREIGN KEY (PROCESSDEF_ID) REFERENCES BPM_PROCESSDEF(PROCESSDEF_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYDEF (
    ACTIVITYDEF_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEF_ID VARCHAR(64),
    PROCESSDEF_VERSION_ID VARCHAR(64),
    DEFNAME VARCHAR(255),
    DESCRIPTION VARCHAR(1024),
    POSITION VARCHAR(32),
    IMPLEMENTATION VARCHAR(32),
    EXECCLASS VARCHAR(512),
    LIMITTIME INT DEFAULT 0,
    ALERTTIME INT DEFAULT 0,
    DURATIONUNIT VARCHAR(16),
    DEADLINEOPERATION VARCHAR(32),
    CANROUTEBACK VARCHAR(16),
    ROUTEBACKMETHOD VARCHAR(32),
    CANSPECIALSEND VARCHAR(16),
    INJOIN VARCHAR(32),
    SPLIT VARCHAR(32),
    FOREIGN KEY (PROCESSDEF_ID) REFERENCES BPM_PROCESSDEF(PROCESSDEF_ID),
    FOREIGN KEY (PROCESSDEF_VERSION_ID) REFERENCES BPM_PROCESSDEF_VERSION(PROCESSDEF_VERSION_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ROUTEDEF (
    ROUTEDEF_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEF_ID VARCHAR(64),
    PROCESSDEF_VERSION_ID VARCHAR(64),
    ROUTENAME VARCHAR(255),
    DESCRIPTION VARCHAR(1024),
    FROMACTIVITYDEF_ID VARCHAR(64),
    TOACTIVITYDEF_ID VARCHAR(64),
    ROUTEORDER INT DEFAULT 0,
    ROUTEDIRECTION VARCHAR(32),
    ROUTECONDITION VARCHAR(2048),
    ROUTECONDITIONTYPE VARCHAR(32),
    FOREIGN KEY (PROCESSDEF_ID) REFERENCES BPM_PROCESSDEF(PROCESSDEF_ID),
    FOREIGN KEY (PROCESSDEF_VERSION_ID) REFERENCES BPM_PROCESSDEF_VERSION(PROCESSDEF_VERSION_ID)
);

CREATE TABLE IF NOT EXISTS BPM_PROCESSINST (
    PROCESSINST_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEF_ID VARCHAR(64),
    PROCESSDEFVERSION_ID VARCHAR(64),
    PROCESSINST_NAME VARCHAR(255),
    URGENCY VARCHAR(16),
    STATE VARCHAR(32),
    COPYNUMBER INT DEFAULT 0,
    STARTTIME BIGINT,
    LIMITTIME BIGINT,
    ENDTIME BIGINT,
    RUNSTATUS VARCHAR(32),
    FOREIGN KEY (PROCESSDEF_ID) REFERENCES BPM_PROCESSDEF(PROCESSDEF_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYINST (
    ACTIVITYINST_ID VARCHAR(64) PRIMARY KEY,
    PROCESSINST_ID VARCHAR(64),
    PROCESSDEF_ID VARCHAR(64),
    ACTIVITYDEF_ID VARCHAR(64),
    ACTIVITYINST_NAME VARCHAR(255),
    STATE VARCHAR(32),
    URGENCY VARCHAR(16),
    ARRIVEDTIME BIGINT,
    LIMITTIME BIGINT,
    ALERTTIME BIGINT,
    STARTTIME BIGINT,
    RECEIVEMETHOD VARCHAR(32),
    DEALMETHOD VARCHAR(32),
    RUNSTATUS VARCHAR(32),
    FOREIGN KEY (PROCESSINST_ID) REFERENCES BPM_PROCESSINST(PROCESSINST_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYINSTHISTORY (
    ACTIVITYINSTHISTORY_ID VARCHAR(64) PRIMARY KEY,
    PROCESSINST_ID VARCHAR(64),
    ACTIVITYDEF_ID VARCHAR(64),
    ACTIVITYINST_NAME VARCHAR(255),
    STATE VARCHAR(32),
    STARTTIME BIGINT,
    ENDTIME BIGINT,
    DEALERID VARCHAR(64),
    FOREIGN KEY (PROCESSINST_ID) REFERENCES BPM_PROCESSINST(PROCESSINST_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ROUTEINST (
    ROUTEINST_ID VARCHAR(64) PRIMARY KEY,
    PROCESSINST_ID VARCHAR(64),
    FROMACTIVITYINSTHISTORY_ID VARCHAR(64),
    TOACTIVITYINST_ID VARCHAR(64),
    ROUTEDEF_ID VARCHAR(64),
    CREATETIME BIGINT,
    FOREIGN KEY (PROCESSINST_ID) REFERENCES BPM_PROCESSINST(PROCESSINST_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ATTRIBUTEDEF (
    ATTRIBUTEDEF_ID VARCHAR(64) PRIMARY KEY,
    ACTIVITYDEF_ID VARCHAR(64),
    PARENT_ID VARCHAR(64),
    ATTRIBUTENAME VARCHAR(128),
    ATTRIBUTETYPE VARCHAR(64),
    ATTRIBUTEVALUE TEXT,
    INTERPRETEDVALUE TEXT,
    FOREIGN KEY (ACTIVITYDEF_ID) REFERENCES BPM_ACTIVITYDEF(ACTIVITYDEF_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYDEF_PROPERTY (
    PROPERTY_ID VARCHAR(64) PRIMARY KEY,
    ACTIVITYDEF_ID VARCHAR(64),
    PROPNAME VARCHAR(128),
    PROPVALUE TEXT,
    PROPCLASS VARCHAR(512),
    PROPTYPE VARCHAR(64),
    PARENTPROP_ID VARCHAR(64),
    ISEXTENSION INT DEFAULT 0,
    CANINSTANTIATE VARCHAR(16),
    FOREIGN KEY (ACTIVITYDEF_ID) REFERENCES BPM_ACTIVITYDEF(ACTIVITYDEF_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ATTRIBUTEINST (
    ATTRIBUTEINST_ID VARCHAR(64) PRIMARY KEY,
    PROCESSINST_ID VARCHAR(64),
    ACTIVITYINST_ID VARCHAR(64),
    PARENT_ID VARCHAR(64),
    ATTRIBUTENAME VARCHAR(128),
    ATTRIBUTETYPE VARCHAR(64),
    ATTRIBUTEVALUE TEXT,
    INTERPRETEDVALUE TEXT,
    FOREIGN KEY (PROCESSINST_ID) REFERENCES BPM_PROCESSINST(PROCESSINST_ID)
);

CREATE TABLE IF NOT EXISTS BPM_USER (
    USER_ID VARCHAR(64) PRIMARY KEY,
    USERNAME VARCHAR(128),
    DISPLAYNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    DEPARTMENT VARCHAR(255),
    STATUS VARCHAR(32) DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYINST_PARTICIPANT (
    PARTICIPANT_ID VARCHAR(64) PRIMARY KEY,
    ACTIVITYINST_ID VARCHAR(64),
    USER_ID VARCHAR(64),
    ROLE_TYPE VARCHAR(32),
    PARTICIPANT_TYPE VARCHAR(32),
    ASSIGNED_TIME BIGINT,
    CLAIMED_TIME BIGINT,
    FOREIGN KEY (ACTIVITYINST_ID) REFERENCES BPM_ACTIVITYINST(ACTIVITYINST_ID),
    FOREIGN KEY (USER_ID) REFERENCES BPM_USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS BPM_PROCESSDEF_PARTICIPANT (
    PARTICIPANT_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEF_ID VARCHAR(64),
    ACTIVITYDEF_ID VARCHAR(64),
    USER_ID VARCHAR(64),
    ROLE_TYPE VARCHAR(32),
    PARTICIPANT_TYPE VARCHAR(32),
    FOREIGN KEY (PROCESSDEF_ID) REFERENCES BPM_PROCESSDEF(PROCESSDEF_ID),
    FOREIGN KEY (USER_ID) REFERENCES BPM_USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS BPM_LISTENER (
    LISTENER_ID VARCHAR(64) PRIMARY KEY,
    OWNER_ID VARCHAR(64),
    OWNERTYPE VARCHAR(32),
    EVENTTYPE VARCHAR(64),
    LISTENERCLASS VARCHAR(512),
    EXECUTEMETHOD VARCHAR(128),
    EXPRESSION VARCHAR(2048),
    EXECORDER INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYLISTENER (
    LISTENER_ID VARCHAR(64) PRIMARY KEY,
    ACTIVITYDEF_ID VARCHAR(64),
    LISTENERNAME VARCHAR(255),
    LISTENERREGISTEVENT VARCHAR(64),
    REALIZECLASS VARCHAR(512),
    EXPRESSIONSTR VARCHAR(2048),
    EXPRESSIONLISENTERTYPE VARCHAR(64),
    EXPRESSIONEVENTTYPE VARCHAR(64),
    FOREIGN KEY (ACTIVITYDEF_ID) REFERENCES BPM_ACTIVITYDEF(ACTIVITYDEF_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ROUTEDEF_PROPERTY (
    PROPERTY_ID VARCHAR(64) PRIMARY KEY,
    ROUTEDEF_ID VARCHAR(64),
    PROPNAME VARCHAR(128),
    PROPVALUE TEXT,
    PROPCLASS VARCHAR(512),
    PROPTYPE VARCHAR(64),
    PARENTPROP_ID VARCHAR(64),
    ISEXTENSION INT DEFAULT 0,
    CANINSTANTIATE VARCHAR(16),
    FOREIGN KEY (ROUTEDEF_ID) REFERENCES BPM_ROUTEDEF(ROUTEDEF_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ROUTELISTENER (
    LISTENER_ID VARCHAR(64) PRIMARY KEY,
    ROUTEDEF_ID VARCHAR(64),
    LISTENERNAME VARCHAR(255),
    LISTENERREGISTEVENT VARCHAR(64),
    REALIZECLASS VARCHAR(512),
    EXPRESSIONSTR VARCHAR(2048),
    EXPRESSIONLISENTERTYPE VARCHAR(64),
    EXPRESSIONEVENTTYPE VARCHAR(64),
    FOREIGN KEY (ROUTEDEF_ID) REFERENCES BPM_ROUTEDEF(ROUTEDEF_ID)
);
