CREATE TABLE IF NOT EXISTS BPM_PROCESSDEF (
    PROCESSDEF_ID VARCHAR(64) PRIMARY KEY,
    DEFNAME VARCHAR(255),
    DESCRIPTION VARCHAR(1024),
    CLASSIFICATION VARCHAR(64),
    SYSTEMCODE VARCHAR(32),
    ACCESSLEVEL VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS BPM_PROCESSDEFVERSION (
    PROCESSDEFVERSION_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEF_ID VARCHAR(64),
    VERSION INT,
    STATE VARCHAR(32),
    CREATETIME BIGINT,
    DESCRIPTION VARCHAR(1024),
    FOREIGN KEY (PROCESSDEF_ID) REFERENCES BPM_PROCESSDEF(PROCESSDEF_ID)
);

CREATE TABLE IF NOT EXISTS BPM_PROCESSINSTANCE (
    PROCESSINST_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEF_ID VARCHAR(64),
    PROCESSDEFVERSION_ID VARCHAR(64),
    PROCESSINST_NAME VARCHAR(255),
    URGENCY VARCHAR(16),
    STATE VARCHAR(32),
    COPYNUMBER INT,
    STARTTIME BIGINT,
    LIMITTIME BIGINT,
    ENDTIME BIGINT,
    RUNSTATUS VARCHAR(32),
    FOREIGN KEY (PROCESSDEF_ID) REFERENCES BPM_PROCESSDEF(PROCESSDEF_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYDEF (
    ACTIVITYDEF_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEFVERSION_ID VARCHAR(64),
    ACTIVITYDEF_NAME VARCHAR(255),
    ACTIVITYDEF_TYPE VARCHAR(32),
    DESCRIPTION VARCHAR(1024),
    ORDERNUM INT,
    FOREIGN KEY (PROCESSDEFVERSION_ID) REFERENCES BPM_PROCESSDEFVERSION(PROCESSDEFVERSION_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYINSTANCE (
    ACTIVITYINST_ID VARCHAR(64) PRIMARY KEY,
    PROCESSINST_ID VARCHAR(64),
    ACTIVITYDEF_ID VARCHAR(64),
    ACTIVITYINST_NAME VARCHAR(255),
    STATE VARCHAR(32),
    STARTTIME BIGINT,
    ENDTIME BIGINT,
    FOREIGN KEY (PROCESSINST_ID) REFERENCES BPM_PROCESSINSTANCE(PROCESSINST_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ROUTEDEF (
    ROUTEDEF_ID VARCHAR(64) PRIMARY KEY,
    PROCESSDEFVERSION_ID VARCHAR(64),
    FROM_ACTIVITYDEF_ID VARCHAR(64),
    TO_ACTIVITYDEF_ID VARCHAR(64),
    ROUTEDEF_NAME VARCHAR(255),
    CONDITION VARCHAR(1024),
    FOREIGN KEY (PROCESSDEFVERSION_ID) REFERENCES BPM_PROCESSDEFVERSION(PROCESSDEFVERSION_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ROUTEINSTANCE (
    ROUTEINST_ID VARCHAR(64) PRIMARY KEY,
    PROCESSINST_ID VARCHAR(64),
    FROM_ACTIVITYINSTHISTORY_ID VARCHAR(64),
    TO_ACTIVITYINST_ID VARCHAR(64),
    ROUTEDEF_ID VARCHAR(64),
    CREATETIME BIGINT,
    FOREIGN KEY (PROCESSINST_ID) REFERENCES BPM_PROCESSINSTANCE(PROCESSINST_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ACTIVITYINSTHISTORY (
    ACTIVITYINSTHISTORY_ID VARCHAR(64) PRIMARY KEY,
    PROCESSINST_ID VARCHAR(64),
    ACTIVITYDEF_ID VARCHAR(64),
    ACTIVITYINST_NAME VARCHAR(255),
    STATE VARCHAR(32),
    STARTTIME BIGINT,
    ENDTIME BIGINT,
    FOREIGN KEY (PROCESSINST_ID) REFERENCES BPM_PROCESSINSTANCE(PROCESSINST_ID)
);

CREATE TABLE IF NOT EXISTS BPM_ATTRIBUTEINST (
    ATTRIBUTEINST_ID VARCHAR(64) PRIMARY KEY,
    PROCESSINST_ID VARCHAR(64),
    ACTIVITYINST_ID VARCHAR(64),
    PARENT_ID VARCHAR(64),
    ATTRIBUTENAME VARCHAR(128),
    ATTRIBUTETYPE VARCHAR(64),
    ATTRIBUTEVALUE TEXT,
    INTERPRETEDVALUE TEXT,
    FOREIGN KEY (PROCESSINST_ID) REFERENCES BPM_PROCESSINSTANCE(PROCESSINST_ID)
);
