apiVersion: skill.ooder.net/v1
kind: SkillManifest

metadata:
  id: skill-health
  name: Health Check Service
  version: 0.7.3
  description: Provides system health check, service check and report generation capabilities
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/skills
  repository: https://github.com/ooderCN/skills.git
  keywords:
    - health
    - check
    - monitor
    - service
    - report

spec:
  type: tool-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.health.HealthSkillApplication
  
  capabilities:
    - id: health-check
      name: Health Check
      description: Run system health checks
      category: health
    - id: service-check
      name: Service Check
      description: Check individual service status
      category: health
    - id: report-generation
      name: Report Generation
      description: Generate health reports
      category: health
  
  scenes:
    - name: health
      description: Health check scene
      capabilities:
        - health-check
        - service-check
        - report-generation
  
  dependencies:
    skills: []
    libraries: []
  
  config:
    required: []
    optional:
      - name: CHECK_INTERVAL
        type: integer
        default: 60000
        description: Health check interval in milliseconds
      - name: TIMEOUT
        type: integer
        default: 5000
        description: Check timeout in milliseconds
  
  endpoints:
    - path: /api/health/check
      method: POST
      description: Run health check
      capability: health-check
    - path: /api/health/services
      method: GET
      description: List all services
      capability: service-check
    - path: /api/health/services/{serviceName}/check
      method: POST
      description: Check specific service
      capability: service-check
    - path: /api/health/report
      method: POST
      description: Generate health report
      capability: report-generation
    - path: /api/health/schedule
      method: POST
      description: Schedule health check
      capability: health-check
    - path: /api/health/status
      method: GET
      description: Get overall health status
      capability: health-check
  
  resources:
    cpu: "100m"
    memory: "128Mi"
    storage: "50Mi"
  
  offline:
    enabled: true
    cacheStrategy: "local"
    syncOnReconnect: true
