apiVersion: skill.ooder.net/v1
kind: Skill

metadata:
  id: skill-vfs-database
  name: Database Storage Service
  version: 0.7.0
  description: Database storage implementation for VFS, supports MySQL/PostgreSQL etc.
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/ooder-skills/tree/main/skills/skill-vfs-database
  repository: https://github.com/ooderCN/ooder-skills.git
  keywords:
    - database
    - mysql
    - postgresql
    - vfs
    - storage
  maintainers:
    - name: Ooder Team
      email: team@ooder.net
      github: ooderCN

spec:
  type: enterprise-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.vfs.database.DatabaseVfsApplication
    jvmOpts: "-Xms256m -Xmx512m"
  
  vfsCapabilities:
    supported:
      - id: file-read
        name: File Read
        description: Read file content
        fallback: none
      - id: file-write
        name: File Write
        description: Write file content
        fallback: none
      - id: file-delete
        name: File Delete
        description: Delete file
        fallback: none
      - id: file-copy
        name: File Copy
        description: Copy file
        fallback: none
      - id: file-move
        name: File Move
        description: Move file
        fallback: none
      - id: folder-create
        name: Folder Create
        description: Create folder
        fallback: none
      - id: folder-delete
        name: Folder Delete
        description: Delete folder
        fallback: none
      - id: folder-list
        name: Folder List
        description: List folder contents
        fallback: none
      - id: file-version
        name: File Versioning
        description: File version management
        fallback: none
      - id: file-compress
        name: File Compression
        description: Compress/decompress files
        fallback: none
      - id: stream-download
        name: Stream Download
        description: Stream download large files
        fallback: none
      - id: acl-manage
        name: ACL Management
        description: Access control list management
        fallback: none
      - id: metadata
        name: Metadata
        description: Custom metadata
        fallback: none
    notSupported:
      - id: file-share
        name: File Sharing
        description: Generate share links
        fallback: none
        fallbackDescription: Database storage does not support sharing
      - id: file-preview
        name: File Preview
        description: Online preview
        fallback: none
        fallbackDescription: Database storage does not support preview
      - id: stream-upload
        name: Stream Upload
        description: Chunked upload large files
        fallback: none
        fallbackDescription: Database storage uses direct write
  
  capabilities:
    - id: vfs-storage
      name: VFS Storage
      description: Database storage operations
      category: storage
      parameters:
        - name: operation
          type: string
          required: true
          description: Operation type (read/write/delete/list)
      returns:
        type: object
        description: Operation result
  
  scenes:
    - name: vfs-database
      description: Database storage scene
      capabilities:
        - vfs-storage
      roles:
        - roleId: vfs-provider
          name: VFS Provider
          required: true
          capabilities: [vfs-storage]
        - roleId: vfs-consumer
          name: VFS Consumer
          required: false
          capabilities: [vfs-storage]
      communicationProtocol: http
      securityPolicy: api-key
      allowParallel: true
  
  dependencies:
    skills: []
    libraries:
      - group: org.springframework.boot
        artifact: spring-boot-starter-web
        version: "2.7.0"
        scope: compile
      - group: org.springframework.boot
        artifact: spring-boot-starter-jdbc
        version: "2.7.0"
        scope: compile
  
  config:
    required:
      - name: VFS_DB_URL
        type: string
        description: Database connection URL
        default: jdbc:mysql://localhost:3306/vfs
        secret: false
      - name: VFS_DB_USERNAME
        type: string
        description: Database username
        default: root
        secret: false
      - name: VFS_DB_PASSWORD
        type: string
        description: Database password
        default: ""
        secret: true
    optional:
      - name: VFS_FILE_PATH
        type: string
        description: File storage path
        default: ./data/vfs-files
        secret: false
      - name: VFS_DB_POOL_SIZE
        type: number
        description: Database connection pool size
        default: 10
        secret: false
  
  endpoints:
    - path: /api/vfs/file/{id}
      method: GET
      description: Get file info
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/file
      method: POST
      description: Upload file
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/file/{id}/download
      method: GET
      description: Download file
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/folder/{id}
      method: GET
      description: Get folder info
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/folder
      method: POST
      description: Create folder
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/capabilities
      method: GET
      description: Get supported capabilities
      authentication: false
  
  resources:
    cpu: "500m"
    memory: "512Mi"
    storage: "50Gi"
    network:
      ingress: true
      egress: false
      ports:
        - 8080
  
  deployment:
    modes:
      - remote-hosted
      - local-deployed
    singleton: false
    requiresAuth: true
    healthCheck:
      path: /actuator/health
      interval: 30
      timeout: 10
    startup:
      timeout: 60
      order: 5
