apiVersion: skill.ooder.net/v1
kind: Skill

metadata:
  id: skill-org-dingding
  name: DingTalk Organization Service
  version: 0.7.1
  description: 钉钉组织数据集成服务，包括组织架构同步和用户认证
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/ooder-skills/tree/main/skills/skill-org-dingding
  repository: https://github.com/ooderCN/ooder-skills.git
  keywords:
    - dingding
    - dingtalk
    - organization
    - enterprise
    - authentication

spec:
  type: enterprise-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.org.dingding.DingTalkOrgSkillApplication
  
  capabilities:
    - id: org-data-read
      name: Organization Data Read
      description: 读取钉钉组织架构和成员数据
      category: data-access
      parameters:
        - name: orgId
          type: string
          required: false
          description: 组织ID
      returns:
        type: object
        description: 组织树和成员
    
    - id: user-auth
      name: User Authentication
      description: 通过钉钉OAuth认证用户
      category: authentication
      parameters:
        - name: code
          type: string
          required: true
          description: 钉钉授权码
      returns:
        type: object
        description: 认证结果
  
  scenes:
    - name: auth
      description: 认证场景
      capabilities:
        - org-data-read
        - user-auth
  
  config:
    required:
      - name: DINGTALK_APP_KEY
        type: string
        description: 钉钉应用Key
        secret: false
      - name: DINGTALK_APP_SECRET
        type: string
        description: 钉钉应用Secret
        secret: true
    optional:
      - name: DINGTALK_API_BASE_URL
        type: string
        description: 钉钉API基础URL
        default: https://oapi.dingtalk.com
        secret: false
  
  endpoints:
    - path: /api/info
      method: GET
      description: 获取技能信息
    - path: /api/org/tree
      method: GET
      description: 获取组织树
      capability: org-data-read
    - path: /api/auth/verify
      method: POST
      description: 验证用户认证
      capability: user-auth
    - path: /api/health
      method: GET
      description: 健康检查
  
  resources:
    cpu: "500m"
    memory: "512Mi"
    storage: "1Gi"

  deployment:
    modes:
      - remote-hosted
      - local-deployed
    singleton: true
