server:
  port: 8084

spring:
  application:
    name: skill-scene

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    net.ooder: DEBUG

ooder:
  jds:
    server:
      home: ./
    config:
      name: scene
  sdk:
    enabled: true
  gitee:
    token: 4bb9dd63de689f07ed7cbad19248af3d
    owner: ooderCN
    skills-repo: skills
  github:
    token: 
    owner: oodercn
    skills-repo: skills
  mock:
    enabled: false
  llm:
    provider: baidu
    model: bce-v3
    baidu:
      api-key: ALTAK-y3mXQFRWjd26xOkkewFpB
      secret-key: e67462d98404432921816438d1a9e66528562839
