apiVersion: ooder.io/v1
kind: SkillPackage

metadata:
  name: skill-vfs-s3
  version: 0.7.3
  description: AWS S3存储服务 - 提供对象存储能力，支持AWS S3接口
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/ooder-skills/tree/main/skills/skill-vfs-s3
  repository: https://github.com/ooderCN/ooder-skills.git
  giteeMirror: https://gitee.com/ooderCN/ooder-skills.git
  keywords:
    - s3
    - aws
    - vfs
    - storage
    - object-storage

spec:
  type: enterprise-skill
  
  capabilities:
    - vfs-storage
    - file-read
    - file-write
    - file-delete
    - metadata

  scenes:
    - vfs-s3

  parameters:
    - name: S3_ENDPOINT
      type: string
      required: true
      description: S3服务端点
    - name: S3_ACCESS_KEY
      type: string
      required: true
      description: S3访问密钥
    - name: S3_SECRET_KEY
      type: string
      required: true
      secret: true
      description: S3秘密密钥
    - name: S3_BUCKET_NAME
      type: string
      required: true
      description: S3桶名称
    - name: S3_REGION
      type: string
      required: false
      default: us-east-1
      description: S3区域

  execution:
    timeout: 30000
    memoryLimit: 512M
    cpuLimit: 1

  distribution:
    format: jar
    entrypoint: net.ooder.skill.vfs.s3.S3VfsApplication
    assets:
      - name: skill-vfs-s3-0.7.3.jar
        platform: all
        url: https://github.com/ooderCN/ooder-skills/releases/download/v0.7.3/skill-vfs-s3-0.7.3.jar
        giteeUrl: https://gitee.com/ooderCN/ooder-skills/releases/download/v0.7.3/skill-vfs-s3-0.7.3.jar

  compatibility:
    sdkVersion: ">=0.7.0"
    javaVersion: ">=8"