apiVersion: skill.ooder.net/v1
kind: Skill

metadata:
  id: skill-vfs-s3
  name: S3 Compatible Object Storage Service
  version: 0.7.0
  description: S3 compatible object storage implementation, supports MinIO, AWS S3, Aliyun OSS, Tencent COS
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/ooder-skills/tree/main/skills/skill-vfs-s3
  repository: https://github.com/ooderCN/ooder-skills.git
  keywords:
    - s3
    - minio
    - oss
    - object-storage
    - vfs
  maintainers:
    - name: Ooder Team
      email: team@ooder.net
      github: ooderCN

spec:
  type: enterprise-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.vfs.s3.S3VfsApplication
    jvmOpts: "-Xms256m -Xmx512m"
  
  vfsCapabilities:
    supported:
      - id: file-read
        name: File Read
        description: Read file content
        fallback: none
      - id: file-write
        name: File Write
        description: Write file content
        fallback: none
      - id: file-delete
        name: File Delete
        description: Delete file
        fallback: none
      - id: file-copy
        name: File Copy
        description: Copy file
        fallback: none
      - id: file-move
        name: File Move
        description: Move file
        fallback: none
      - id: folder-create
        name: Folder Create
        description: Create folder
        fallback: none
      - id: folder-delete
        name: Folder Delete
        description: Delete folder
        fallback: none
      - id: folder-list
        name: Folder List
        description: List folder contents
        fallback: none
      - id: file-version
        name: File Versioning
        description: File version management
        fallback: none
      - id: stream-download
        name: Stream Download
        description: Stream download large files
        fallback: none
      - id: stream-upload
        name: Stream Upload
        description: Chunked upload large files
        fallback: none
      - id: file-share
        name: File Sharing
        description: Generate share links
        fallback: none
      - id: metadata
        name: Metadata
        description: Custom metadata
        fallback: none
    notSupported:
      - id: file-preview
        name: File Preview
        description: Online preview
        fallback: none
        fallbackDescription: S3 storage does not support preview directly
      - id: acl-manage
        name: ACL Management
        description: Access control list management
        fallback: none
        fallbackDescription: S3 uses bucket policies
  
  capabilities:
    - id: vfs-storage
      name: VFS Storage
      description: S3 compatible object storage operations
      category: storage
      parameters:
        - name: operation
          type: string
          required: true
          description: Operation type (read/write/delete/list)
      returns:
        type: object
        description: Operation result
  
  scenes:
    - name: vfs-s3
      description: S3 object storage scene
      capabilities:
        - vfs-storage
      roles:
        - roleId: vfs-provider
          name: VFS Provider
          required: true
          capabilities: [vfs-storage]
        - roleId: vfs-consumer
          name: VFS Consumer
          required: false
          capabilities: [vfs-storage]
      communicationProtocol: http
      securityPolicy: api-key
      allowParallel: true
  
  dependencies:
    skills: []
    libraries:
      - group: org.springframework.boot
        artifact: spring-boot-starter-web
        version: "2.7.0"
        scope: compile
      - group: com.amazonaws
        artifact: aws-java-sdk-s3
        version: "1.12.400"
        scope: compile
  
  config:
    required:
      - name: S3_ENDPOINT
        type: string
        description: S3 endpoint URL
        default: ""
        secret: false
      - name: S3_ACCESS_KEY
        type: string
        description: Access key
        default: ""
        secret: true
      - name: S3_SECRET_KEY
        type: string
        description: Secret key
        default: ""
        secret: true
      - name: S3_BUCKET
        type: string
        description: Bucket name
        default: vfs-storage
        secret: false
    optional:
      - name: S3_REGION
        type: string
        description: Region
        default: us-east-1
        secret: false
      - name: S3_PATH_STYLE
        type: boolean
        description: Use path style access
        default: true
        secret: false
  
  endpoints:
    - path: /api/vfs/file/{id}
      method: GET
      description: Get file info
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/file
      method: POST
      description: Upload file
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/file/{id}/download
      method: GET
      description: Download file
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/folder/{id}
      method: GET
      description: Get folder info
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/folder
      method: POST
      description: Create folder
      capability: vfs-storage
      authentication: true
    - path: /api/vfs/capabilities
      method: GET
      description: Get supported capabilities
      authentication: false
  
  resources:
    cpu: "500m"
    memory: "512Mi"
    storage: "100Gi"
    network:
      ingress: true
      egress: true
      ports:
        - 8080
  
  deployment:
    modes:
      - remote-hosted
      - local-deployed
    singleton: false
    requiresAuth: true
    healthCheck:
      path: /actuator/health
      interval: 30
      timeout: 10
    startup:
      timeout: 60
      order: 5
