apiVersion: skill.ooder.net/v1
kind: SkillManifest

metadata:
  id: skill-hosting
  name: Hosting Service Skill
  version: 0.7.3
  description: Provides container hosting, instance management, and resource quota capabilities
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/skills
  repository: https://github.com/ooderCN/skills.git
  keywords:
    - hosting
    - container
    - instance
    - kubernetes
    - docker

spec:
  type: tool-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.hosting.HostingSkillApplication
  
  capabilities:
    - id: instance-management
      name: Instance Management
      description: Create, update, delete and manage instances
      category: hosting
    - id: resource-quota
      name: Resource Quota
      description: Manage resource quotas and limits
      category: hosting
    - id: health-monitoring
      name: Health Monitoring
      description: Monitor instance health and metrics
      category: hosting
  
  scenes:
    - name: hosting
      description: Hosting service scene
      capabilities:
        - instance-management
        - resource-quota
        - health-monitoring
  
  dependencies:
    skills: []
    libraries: []
  
  config:
    required: []
    optional:
      - name: HOSTING_MAX_INSTANCES
        type: integer
        default: 100
        description: Maximum instances
      - name: HOSTING_MAX_CPU_CORES
        type: integer
        default: 16
        description: Maximum CPU cores
      - name: HOSTING_MAX_MEMORY_MB
        type: integer
        default: 32768
        description: Maximum memory in MB
  
  endpoints:
    - path: /api/hosting/instances
      method: GET
      description: Get all instances
      capability: instance-management
    - path: /api/hosting/instances
      method: POST
      description: Create instance
      capability: instance-management
    - path: /api/hosting/instances/{id}
      method: GET
      description: Get instance
      capability: instance-management
    - path: /api/hosting/instances/{id}
      method: PUT
      description: Update instance
      capability: instance-management
    - path: /api/hosting/instances/{id}
      method: DELETE
      description: Delete instance
      capability: instance-management
    - path: /api/hosting/instances/{id}/start
      method: POST
      description: Start instance
      capability: instance-management
    - path: /api/hosting/instances/{id}/stop
      method: POST
      description: Stop instance
      capability: instance-management
    - path: /api/hosting/instances/{id}/restart
      method: POST
      description: Restart instance
      capability: instance-management
    - path: /api/hosting/instances/{id}/scale
      method: POST
      description: Scale instance
      capability: instance-management
    - path: /api/hosting/instances/{id}/health
      method: GET
      description: Get instance health
      capability: health-monitoring
    - path: /api/hosting/instances/{id}/metrics
      method: GET
      description: Get instance metrics
      capability: health-monitoring
    - path: /api/hosting/instances/{id}/logs
      method: GET
      description: Get instance logs
      capability: health-monitoring
    - path: /api/hosting/quota
      method: GET
      description: Get quota
      capability: resource-quota
  
  resources:
    cpu: "200m"
    memory: "256Mi"
    storage: "100Mi"
  
  offline:
    enabled: false
