package net.ooder.scene.llm.config.generator;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import net.ooder.scene.llm.LlmService;
import net.ooder.scene.llm.SceneChatRequest;
import net.ooder.sdk.llm.tool.ChatResponse;
import net.ooder.scene.llm.config.layered.LlmConfigProperties;
import net.ooder.scene.llm.config.skillsmd.SkillsMdDocument;
import net.ooder.scene.llm.config.skillsmd.CapabilityDefinition;
import net.ooder.scene.llm.config.skillsmd.ParameterDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LlmConfigGeneratorService {

    private static final Logger log = LoggerFactory.getLogger(LlmConfigGeneratorService.class);

    private static final String SYSTEM_PROMPT = buildSystemPrompt();

    private final LlmService llmService;
    private final ObjectMapper yamlMapper;

    public LlmConfigGeneratorService(LlmService llmService) {
        this.llmService = llmService;
        this.yamlMapper = new ObjectMapper(new YAMLFactory());
    }

    public LlmConfigProperties generateConfig(SkillsMdDocument document) {
        return generateConfig(document, null);
    }

    public LlmConfigProperties generateConfig(SkillsMdDocument document, String userRequirements) {
        log.info("Generating LLM config for skill: {}", document.getName());

        String userPrompt = buildUserPrompt(document, userRequirements);

        SceneChatRequest request = new SceneChatRequest()
            .system(SYSTEM_PROMPT)
            .user(userPrompt)
            .temperature(0.3)
            .maxTokens(4096);

        try {
            ChatResponse response = llmService.chat(request);
            if (response != null && response.getContent() != null) {
                String yamlContent = extractYaml(response.getContent());
                return yamlMapper.readValue(yamlContent, LlmConfigProperties.class);
            }
        } catch (Exception e) {
            log.error("Failed to generate config: {}", e.getMessage(), e);
        }

        return generateDefaultConfig(document);
    }

    public Path generateAndSaveConfig(SkillsMdDocument document, Path targetPath) throws IOException {
        return generateAndSaveConfig(document, targetPath, null);
    }

    public Path generateAndSaveConfig(SkillsMdDocument document, Path targetPath, String userRequirements) throws IOException {
        LlmConfigProperties config = generateConfig(document, userRequirements);

        if (targetPath == null) {
            String userHome = System.getProperty("user.home");
            targetPath = Paths.get(userHome, ".ooder", "skills", document.getName(), "skill-config.yaml");
        }

        Files.createDirectories(targetPath.getParent());

        String yamlContent = yamlMapper.writerWithDefaultPrettyPrinter().writeValueAsString(config);

        try (BufferedWriter writer = Files.newBufferedWriter(targetPath)) {
            writer.write("# Auto-generated by LLM Config Generator\n");
            writer.write("# Skill: " + document.getName() + "\n");
            writer.write("# Generated at: " + new Date() + "\n\n");
            writer.write(yamlContent);
        }

        log.info("Config saved to: {}", targetPath);
        return targetPath;
    }

    public LlmConfigProperties generateDefaultConfig(SkillsMdDocument document) {
        LlmConfigProperties config = new LlmConfigProperties();
        config.setProvider("openai");
        config.setModel(document.getSuggestedModel() != null ? document.getSuggestedModel() : "gpt-4");
        config.setTemperature(document.getSuggestedTemperature() != null ? document.getSuggestedTemperature() : 0.7);
        config.setMaxTokens(document.getSuggestedMaxTokens() != null ? document.getSuggestedMaxTokens() : 2048);

        Map<String, LlmConfigProperties.FunctionConfig> functions = new HashMap<>();

        for (CapabilityDefinition capability : document.getCapabilities()) {
            LlmConfigProperties.FunctionConfig funcConfig = new LlmConfigProperties.FunctionConfig();
            funcConfig.setName(capability.getName());
            funcConfig.setDescription(capability.getDescription());
            funcConfig.setCapability(capability.getName());

            Map<String, LlmConfigProperties.ParameterConfig> params = new HashMap<>();
            List<String> required = new ArrayList<>();

            if (capability.getParameters() != null) {
                for (ParameterDefinition param : capability.getParameters()) {
                    LlmConfigProperties.ParameterConfig paramConfig = new LlmConfigProperties.ParameterConfig();
                    paramConfig.setType(param.getType());
                    paramConfig.setDescription(param.getDescription());
                    params.put(param.getName(), paramConfig);

                    if (param.isRequired()) {
                        required.add(param.getName());
                    }
                }
            }
            funcConfig.setParameters(params);
            funcConfig.setRequired(required);
            functions.put(capability.getName(), funcConfig);
        }

        config.setFunctions(functions);
        return config;
    }

    private String buildUserPrompt(SkillsMdDocument document, String userRequirements) {
        StringBuilder sb = new StringBuilder();
        sb.append("请根据以下 SKILLS.MD 文档生成 LLM 配置文件:\n\n");
        sb.append("## Skill Name: ").append(document.getName()).append("\n");
        sb.append("## Overview: ").append(document.getOverview()).append("\n\n");

        sb.append("## Capabilities:\n");
        for (CapabilityDefinition cap : document.getCapabilities()) {
            sb.append("- **").append(cap.getName()).append("**: ").append(cap.getDescription()).append("\n");
            if (cap.getParameters() != null && !cap.getParameters().isEmpty()) {
                sb.append("  Parameters:\n");
                for (ParameterDefinition param : cap.getParameters()) {
                    sb.append("  - ").append(param.getName()).append(" (").append(param.getType()).append(")");
                    if (param.isRequired()) sb.append(" [required]");
                    sb.append(": ").append(param.getDescription()).append("\n");
                }
            }
        }

        if (userRequirements != null && !userRequirements.isEmpty()) {
            sb.append("\n## User Requirements:\n").append(userRequirements).append("\n");
        }

        sb.append("\n请生成完整的 YAML 配置文件。");
        return sb.toString();
    }

    private static String buildSystemPrompt() {
        return "You are an expert LLM configuration generator. " +
               "Your task is to analyze SKILLS.MD documents and generate optimal YAML configuration files for LLM-based skill execution.\n\n" +
               "The configuration should include:\n" +
               "1. Provider settings (openai, anthropic, etc.)\n" +
               "2. Model selection based on task complexity\n" +
               "3. Temperature and token limits\n" +
               "4. Function definitions for each capability\n" +
               "5. Parameter mappings with proper types\n" +
               "6. Prompt templates for common scenarios\n\n" +
               "Output only valid YAML, no explanations.";
    }

    private String extractYaml(String content) {
        if (content.contains("```yaml")) {
            int start = content.indexOf("```yaml") + 7;
            int end = content.indexOf("```", start);
            if (end > start) {
                return content.substring(start, end).trim();
            }
        }
        if (content.contains("```yml")) {
            int start = content.indexOf("```yml") + 6;
            int end = content.indexOf("```", start);
            if (end > start) {
                return content.substring(start, end).trim();
            }
        }
        if (content.contains("```")) {
            int start = content.indexOf("```") + 3;
            int end = content.indexOf("```", start);
            if (end > start) {
                return content.substring(start, end).trim();
            }
        }
        return content.trim();
    }
}
