apiVersion: skill.ooder.net/v1
kind: SkillManifest

metadata:
  id: skill-security
  name: Security Management Skill
  version: 0.7.3
  description: Provides user management, permission control, and security audit capabilities
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/skills
  repository: https://github.com/ooderCN/skills.git
  keywords:
    - security
    - user
    - permission
    - auth
    - audit

spec:
  type: tool-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.security.SecuritySkillApplication
  
  capabilities:
    - id: user-management
      name: User Management
      description: Manage users and their profiles
      category: security
    - id: permission-control
      name: Permission Control
      description: Control user permissions and roles
      category: security
    - id: security-audit
      name: Security Audit
      description: Audit security events
      category: security
  
  scenes:
    - name: security
      description: Security management scene
      capabilities:
        - user-management
        - permission-control
        - security-audit
  
  dependencies:
    skills: []
    libraries: []
  
  config:
    required: []
    optional:
      - name: SECURITY_SESSION_TIMEOUT
        type: integer
        default: 1800000
        description: Session timeout in milliseconds
      - name: SECURITY_MAX_LOGIN_ATTEMPTS
        type: integer
        default: 5
        description: Maximum login attempts
      - name: SECURITY_LOCKOUT_DURATION
        type: integer
        default: 1800000
        description: Lockout duration in milliseconds
  
  endpoints:
    - path: /api/security/status
      method: GET
      description: Get security status
      capability: security-audit
    - path: /api/security/users
      method: GET
      description: Get user list
      capability: user-management
    - path: /api/security/users
      method: POST
      description: Add user
      capability: user-management
    - path: /api/security/users/{id}
      method: PUT
      description: Edit user
      capability: user-management
    - path: /api/security/users/{id}
      method: DELETE
      description: Delete user
      capability: user-management
    - path: /api/security/users/{id}/enable
      method: POST
      description: Enable user
      capability: user-management
    - path: /api/security/users/{id}/disable
      method: POST
      description: Disable user
      capability: user-management
    - path: /api/security/permissions
      method: GET
      description: Get permissions
      capability: permission-control
    - path: /api/security/permissions
      method: POST
      description: Save permissions
      capability: permission-control
    - path: /api/security/logs
      method: GET
      description: Get security logs
      capability: security-audit
  
  resources:
    cpu: "200m"
    memory: "256Mi"
    storage: "100Mi"
  
  offline:
    enabled: true
    cacheStrategy: "local"
    syncOnReconnect: true
