apiVersion: ooder.io/v1
kind: SkillPackage

metadata:
  name: skill-trae-solo
  version: 0.7.1
  description: 连接实用功能，运行结果通过A2UI节点展示，支持A2UI图转代码技术集成
  author: Ooder Team
  license: Apache-2.0
  homepage: https://gitee.com/ooderCN/skills/tree/main/skills/skill-trae-solo
  repository: https://gitee.com/ooderCN/skills.git
  keywords:
    - utility
    - integration
    - ui
    - a2ui

spec:
  type: tool-skill
  
  capabilities:
    - execute-task
    - get-info

  scenes:
    - utility

  parameters:
    - name: TRAE_SOLO_PORT
      type: number
      required: false
      default: 8085
      description: 服务端口
    - name: A2UI_ENDPOINT
      type: string
      required: false
      default: http://localhost:8081/api
      description: A2UI服务端点

  execution:
    timeout: 60000
    memoryLimit: 512M
    cpuLimit: 1

  distribution:
    format: jar
    entrypoint: net.ooder.skill.traesolo.TraeSoloSkillApplication
    assets:
      - name: skill-trae-solo-0.7.1.jar
        platform: all
        url: https://gitee.com/ooderCN/skills/releases/download/v0.7.1/skill-trae-solo-0.7.1.jar

  compatibility:
    sdkVersion: ">=0.7.0"
    javaVersion: ">=8"
