apiVersion: skill.ooder.net/v1
kind: SkillManifest

metadata:
  id: skill-agent
  name: Agent Management Service
  version: 0.7.3
  description: Provides terminal agent registration, management and command execution capabilities
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/skills
  repository: https://github.com/ooderCN/skills.git
  keywords:
    - agent
    - terminal
    - management
    - command
    - execution

spec:
  type: tool-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.agent.AgentSkillApplication
  
  capabilities:
    - id: agent-management
      name: Agent Management
      description: Register, update, delete agents
      category: agent
    - id: command-execution
      name: Command Execution
      description: Execute commands on agents
      category: agent
    - id: network-status
      name: Network Status
      description: Get agent network status
      category: agent
  
  scenes:
    - name: agent
      description: Agent management scene
      capabilities:
        - agent-management
        - command-execution
        - network-status
  
  dependencies:
    skills: []
    libraries: []
  
  config:
    required: []
    optional:
      - name: HEARTBEAT_INTERVAL
        type: integer
        default: 30000
        description: Agent heartbeat interval in milliseconds
      - name: OFFLINE_THRESHOLD
        type: integer
        default: 90000
        description: Time threshold to mark agent as offline
  
  endpoints:
    - path: /api/agent/register
      method: POST
      description: Register a new agent
      capability: agent-management
    - path: /api/agent/list
      method: GET
      description: List all agents
      capability: agent-management
    - path: /api/agent/{agentId}
      method: GET
      description: Get agent by ID
      capability: agent-management
    - path: /api/agent/{agentId}
      method: DELETE
      description: Delete an agent
      capability: agent-management
    - path: /api/agent/{agentId}/heartbeat
      method: POST
      description: Agent heartbeat
      capability: agent-management
    - path: /api/agent/{agentId}/command
      method: POST
      description: Execute command on agent
      capability: command-execution
    - path: /api/agent/{agentId}/network
      method: GET
      description: Get agent network status
      capability: network-status
    - path: /api/agent/{agentId}/status
      method: GET
      description: Get agent status
      capability: agent-management
  
  resources:
    cpu: "200m"
    memory: "256Mi"
    storage: "100Mi"
  
  offline:
    enabled: true
    cacheStrategy: "local"
    syncOnReconnect: true
