apiVersion: skill.ooder.net/v1
kind: SkillManifest

metadata:
  id: skill-openwrt
  name: OpenWrt Router Driver
  version: 0.7.3
  description: Provides OpenWrt router connection, configuration and command execution capabilities
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/skills
  repository: https://github.com/ooderCN/skills.git
  keywords:
    - openwrt
    - router
    - uci
    - network
    - driver

spec:
  type: tool-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.openwrt.OpenWrtSkillApplication
  
  capabilities:
    - id: router-connection
      name: Router Connection
      description: Connect to OpenWrt router via SSH/HTTP
      category: openwrt
    - id: uci-config
      name: UCI Configuration
      description: Manage UCI configuration
      category: openwrt
    - id: command-execution
      name: Command Execution
      description: Execute commands on router
      category: openwrt
    - id: wifi-management
      name: WiFi Management
      description: Manage WiFi settings
      category: openwrt
    - id: dhcp-management
      name: DHCP Management
      description: Manage DHCP settings
      category: openwrt
  
  scenes:
    - name: openwrt
      description: OpenWrt management scene
      capabilities:
        - router-connection
        - uci-config
        - command-execution
        - wifi-management
        - dhcp-management
  
  dependencies:
    skills: []
    libraries: []
  
  config:
    required: []
    optional:
      - name: CONNECTION_TIMEOUT
        type: integer
        default: 30000
        description: Connection timeout in milliseconds
      - name: SSH_PORT
        type: integer
        default: 22
        description: SSH port
      - name: HTTP_PORT
        type: integer
        default: 80
        description: HTTP port
  
  endpoints:
    - path: /api/openwrt/connect
      method: POST
      description: Connect to router
      capability: router-connection
    - path: /api/openwrt/disconnect
      method: POST
      description: Disconnect from router
      capability: router-connection
    - path: /api/openwrt/status
      method: GET
      description: Get connection status
      capability: router-connection
    - path: /api/openwrt/info
      method: GET
      description: Get router info
      capability: router-connection
    - path: /api/openwrt/uci/get
      method: GET
      description: Get UCI config
      capability: uci-config
    - path: /api/openwrt/uci/set
      method: POST
      description: Set UCI config
      capability: uci-config
    - path: /api/openwrt/uci/commit
      method: POST
      description: Commit UCI changes
      capability: uci-config
    - path: /api/openwrt/command
      method: POST
      description: Execute command
      capability: command-execution
    - path: /api/openwrt/wifi/list
      method: GET
      description: List WiFi networks
      capability: wifi-management
    - path: /api/openwrt/wifi/update
      method: POST
      description: Update WiFi config
      capability: wifi-management
    - path: /api/openwrt/wifi/scan
      method: POST
      description: Scan WiFi networks
      capability: wifi-management
    - path: /api/openwrt/dhcp/leases
      method: GET
      description: Get DHCP leases
      capability: dhcp-management
    - path: /api/openwrt/packages
      method: GET
      description: List packages
      capability: command-execution
    - path: /api/openwrt/reboot
      method: POST
      description: Reboot router
      capability: command-execution
  
  resources:
    cpu: "200m"
    memory: "256Mi"
    storage: "100Mi"
  
  offline:
    enabled: true
    cacheStrategy: "local"
    syncOnReconnect: true
