// --------------------------------------------------------
// Generated by sql2code - http://sql2java.sourceforge.net/
// --------------------------------------------------------

/**
 * The java object mapped on the Relation database table BPM_PROCESSDEF_PROPERTY
 */
package net.ooder.bpm.engine.database;

import java.io.Serializable;

// imports+

// imports-

public class DbAttribute implements Serializable
// extends+

// extends-
{
	private String propertyId;

	private boolean propertyId_is_modified = false;

	private boolean propertyId_is_initialized = false;

	private String processdefId;

	private boolean processdefId_is_modified = false;

	private boolean processdefId_is_initialized = false;

	private String processdefVersionId;

	private boolean processdefVersionId_is_modified = false;

	private boolean processdefVersionId_is_initialized = false;

	private String propname;

	private boolean propname_is_modified = false;

	private boolean propname_is_initialized = false;

	private String propvalue;

	private boolean propvalue_is_modified = false;

	private boolean propvalue_is_initialized = false;

	private String propclass;

	private boolean propclass_is_modified = false;

	private boolean propclass_is_initialized = false;

	private String proptype;

	private boolean proptype_is_modified = false;

	private boolean proptype_is_initialized = false;

	private String parentpropId;

	private boolean parentpropId_is_modified = false;

	private boolean parentpropId_is_initialized = false;

	private Long isextension;

	private boolean isextension_is_modified = false;

	private boolean isextension_is_initialized = false;

	private String caninstantiate;

	private boolean caninstantiate_is_modified = false;

	private boolean caninstantiate_is_initialized = false;

	private boolean _isNew = true;

	/**
	 */
	DbAttribute() {
	}

	/**
	 * Getter method for propertyId
	 * 
	 * @return the value of propertyId
	 */
	public String getPropertyId() {
		return propertyId;
	}

	/**
	 * Setter method for propertyId
	 * 
	 * @param newVal
	 *            The new value to be assigned to propertyId
	 */
	public void setPropertyId(String newVal) {
		if ((newVal != null && newVal.equals(this.propertyId) == true)
				|| (newVal == null && this.propertyId == null))
			return;
		this.propertyId = newVal;
		propertyId_is_modified = true;
		propertyId_is_initialized = true;
	}

	/**
	 * Determine if the propertyId is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isPropertyIdModified() {
		return propertyId_is_modified;
	}

	/**
	 * Determine if the propertyId has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isPropertyIdInitialized() {
		return propertyId_is_initialized;
	}

	/**
	 * Getter method for processdefId
	 * 
	 * @return the value of processdefId
	 */
	public String getProcessdefId() {
		return processdefId;
	}

	/**
	 * Setter method for processdefId
	 * 
	 * @param newVal
	 *            The new value to be assigned to processdefId
	 */
	public void setProcessdefId(String newVal) {
		if ((newVal != null && newVal.equals(this.processdefId) == true)
				|| (newVal == null && this.processdefId == null))
			return;
		this.processdefId = newVal;
		processdefId_is_modified = true;
		processdefId_is_initialized = true;
	}

	/**
	 * Determine if the processdefId is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isProcessdefIdModified() {
		return processdefId_is_modified;
	}

	/**
	 * Determine if the processdefId has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isProcessdefIdInitialized() {
		return processdefId_is_initialized;
	}

	/**
	 * Getter method for processdefVersionId
	 * 
	 * @return the value of processdefVersionId
	 */
	public String getProcessdefVersionId() {
		return processdefVersionId;
	}

	/**
	 * Setter method for processdefVersionId
	 * 
	 * @param newVal
	 *            The new value to be assigned to processdefVersionId
	 */
	public void setProcessdefVersionId(String newVal) {
		if ((newVal != null && newVal.equals(this.processdefVersionId) == true)
				|| (newVal == null && this.processdefVersionId == null))
			return;
		this.processdefVersionId = newVal;
		processdefVersionId_is_modified = true;
		processdefVersionId_is_initialized = true;
	}

	/**
	 * Determine if the processdefVersionId is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isProcessdefVersionIdModified() {
		return processdefVersionId_is_modified;
	}

	/**
	 * Determine if the processdefVersionId has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isProcessdefVersionIdInitialized() {
		return processdefVersionId_is_initialized;
	}

	/**
	 * Getter method for propname
	 * 
	 * @return the value of propname
	 */
	public String getPropname() {
		return propname;
	}

	/**
	 * Setter method for propname
	 * 
	 * @param newVal
	 *            The new value to be assigned to propname
	 */
	public void setPropname(String newVal) {
		if ((newVal != null && newVal.equals(this.propname) == true)
				|| (newVal == null && this.propname == null))
			return;
		this.propname = newVal;
		propname_is_modified = true;
		propname_is_initialized = true;
	}

	/**
	 * Determine if the propname is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isPropnameModified() {
		return propname_is_modified;
	}

	/**
	 * Determine if the propname has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isPropnameInitialized() {
		return propname_is_initialized;
	}

	/**
	 * Getter method for propvalue
	 * 
	 * @return the value of propvalue
	 */
	public String getPropvalue() {
		return propvalue;
	}

	/**
	 * Setter method for propvalue
	 * 
	 * @param newVal
	 *            The new value to be assigned to propvalue
	 */
	public void setPropvalue(String newVal) {
		if ((newVal != null && newVal.equals(this.propvalue) == true)
				|| (newVal == null && this.propvalue == null))
			return;
		this.propvalue = newVal;
		propvalue_is_modified = true;
		propvalue_is_initialized = true;
	}

	/**
	 * Determine if the propvalue is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isPropvalueModified() {
		return propvalue_is_modified;
	}

	/**
	 * Determine if the propvalue has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isPropvalueInitialized() {
		return propvalue_is_initialized;
	}

	/**
	 * Getter method for propclass
	 * 
	 * @return the value of propclass
	 */
	public String getPropclass() {
		return propclass;
	}

	/**
	 * Setter method for propclass
	 * 
	 * @param newVal
	 *            The new value to be assigned to propclass
	 */
	public void setPropclass(String newVal) {
		if ((newVal != null && newVal.equals(this.propclass) == true)
				|| (newVal == null && this.propclass == null))
			return;
		this.propclass = newVal;
		propclass_is_modified = true;
		propclass_is_initialized = true;
	}

	/**
	 * Determine if the propclass is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isPropclassModified() {
		return propclass_is_modified;
	}

	/**
	 * Determine if the propclass has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isPropclassInitialized() {
		return propclass_is_initialized;
	}

	/**
	 * Getter method for proptype
	 * 
	 * @return the value of proptype
	 */
	public String getProptype() {
		return proptype;
	}

	/**
	 * Setter method for proptype
	 * 
	 * @param newVal
	 *            The new value to be assigned to proptype
	 */
	public void setProptype(String newVal) {
		if ((newVal != null && newVal.equals(this.proptype) == true)
				|| (newVal == null && this.proptype == null))
			return;
		this.proptype = newVal;
		proptype_is_modified = true;
		proptype_is_initialized = true;
	}

	/**
	 * Determine if the proptype is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isProptypeModified() {
		return proptype_is_modified;
	}

	/**
	 * Determine if the proptype has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isProptypeInitialized() {
		return proptype_is_initialized;
	}

	/**
	 * Getter method for parentpropId
	 * 
	 * @return the value of parentpropId
	 */
	public String getParentpropId() {
		return parentpropId;
	}

	/**
	 * Setter method for parentpropId
	 * 
	 * @param newVal
	 *            The new value to be assigned to parentpropId
	 */
	public void setParentpropId(String newVal) {
		if ((newVal != null && newVal.equals(this.parentpropId) == true)
				|| (newVal == null && this.parentpropId == null))
			return;
		this.parentpropId = newVal;
		parentpropId_is_modified = true;
		parentpropId_is_initialized = true;
	}

	/**
	 * Determine if the parentpropId is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isParentpropIdModified() {
		return parentpropId_is_modified;
	}

	/**
	 * Determine if the parentpropId has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isParentpropIdInitialized() {
		return parentpropId_is_initialized;
	}

	/**
	 * Getter method for isextension
	 * 
	 * @return the value of isextension
	 */
	public Long getIsextension() {
		return isextension;
	}

	/**
	 * Setter method for isextension
	 * 
	 * @param newVal
	 *            The new value to be assigned to isextension
	 */
	public void setIsextension(Long newVal) {
		if ((newVal != null && newVal.equals(this.isextension) == true)
				|| (newVal == null && this.isextension == null))
			return;
		this.isextension = newVal;
		isextension_is_modified = true;
		isextension_is_initialized = true;
	}

	/**
	 * Setter method for isextension Convenient setter for those who do not want
	 * to deal with Objects for primary types.
	 * 
	 * @param newVal
	 *            The new value to be assigned to isextension
	 */
	public void setIsextension(long newVal) {
		setIsextension(new Long(newVal));
	}

	/**
	 * Determine if the isextension is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isIsextensionModified() {
		return isextension_is_modified;
	}

	/**
	 * Determine if the isextension has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isIsextensionInitialized() {
		return isextension_is_initialized;
	}

	/**
	 * Getter method for caninstantiate
	 * 
	 * @return the value of caninstantiate
	 */
	public String getCaninstantiate() {
		return caninstantiate;
	}

	/**
	 * Setter method for caninstantiate
	 * 
	 * @param newVal
	 *            The new value to be assigned to caninstantiate
	 */
	public void setCaninstantiate(String newVal) {
		if ((newVal != null && newVal.equals(this.caninstantiate) == true)
				|| (newVal == null && this.caninstantiate == null))
			return;
		this.caninstantiate = newVal;
		caninstantiate_is_modified = true;
		caninstantiate_is_initialized = true;
	}

	/**
	 * Determine if the caninstantiate is modified or not
	 * 
	 * @return true if the field has been modified, false if the field has not
	 *         been modified
	 */
	public boolean isCaninstantiateModified() {
		return caninstantiate_is_modified;
	}

	/**
	 * Determine if the caninstantiate has been initialized or not
	 * 
	 * @return true if the field has been initialized, false otherwise
	 */
	public boolean isCaninstantiateInitialized() {
		return caninstantiate_is_initialized;
	}

	/**
	 * Determine if the current object is new or not
	 * 
	 * @return true if the current object is new, false if the object is not new
	 */
	public boolean isNew() {
		return _isNew;
	}

	/**
	 * Specify to the object if he has to been set as new or not
	 * 
	 * @param isNew
	 *            the boolean value to be assigned to the isNew field
	 */
	public void setIsNew(boolean isNew) {
		this._isNew = isNew;
	}

	/**
	 * Determine if the object has been modified since the last time this method
	 * was called or since the creation of the object
	 * 
	 * @return true if the object has been modified, false if the object has not
	 *         been modified
	 */
	public boolean isModified() {
		return propertyId_is_modified || processdefId_is_modified
				|| processdefVersionId_is_modified || propname_is_modified
				|| propvalue_is_modified || propclass_is_modified
				|| proptype_is_modified || parentpropId_is_modified
				|| isextension_is_modified || caninstantiate_is_modified;
	}

	/**
	 * Reset object modification status to "not modified"
	 */
	public void resetIsModified() {
		propertyId_is_modified = false;
		processdefId_is_modified = false;
		processdefVersionId_is_modified = false;
		propname_is_modified = false;
		propvalue_is_modified = false;
		propclass_is_modified = false;
		proptype_is_modified = false;
		parentpropId_is_modified = false;
		isextension_is_modified = false;
		caninstantiate_is_modified = false;
	}

	/**
	 * Copy the passed bean into the current bean
	 * 
	 * @param bean
	 *            the bean to copy into the current bean
	 */
	public void copy(DbAttribute bean) {
		setPropertyId(bean.getPropertyId());
		setProcessdefId(bean.getProcessdefId());
		setProcessdefVersionId(bean.getProcessdefVersionId());
		setPropname(bean.getPropname());
		setPropvalue(bean.getPropvalue());
		setPropclass(bean.getPropclass());
		setProptype(bean.getProptype());
		setParentpropId(bean.getParentpropId());
		setIsextension(bean.getIsextension());
		setCaninstantiate(bean.getCaninstantiate());
	}

	/**
	 * Return the object string representation
	 * 
	 * @return the object as a string
	 */
	public String toString() {
		return "\n[BPM_PROCESSDEF_PROPERTY] "
				+ "\n - BPM_PROCESSDEF_PROPERTY.PROPERTY_ID = "
				+ (propertyId_is_initialized ? ("[" + propertyId.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.PROCESSDEF_ID = "
				+ (processdefId_is_initialized ? ("[" + processdefId.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.PROCESSDEF_VERSION_ID = "
				+ (processdefVersionId_is_initialized ? ("["
						+ processdefVersionId.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.PROPNAME = "
				+ (propname_is_initialized ? ("[" + propname.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.PROPVALUE = "
				+ (propvalue_is_initialized ? ("[" + propvalue.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.PROPCLASS = "
				+ (propclass_is_initialized ? ("[" + propclass.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.PROPTYPE = "
				+ (proptype_is_initialized ? ("[" + proptype.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.PARENTPROP_ID = "
				+ (parentpropId_is_initialized ? ("[" + parentpropId.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.ISEXTENSION = "
				+ (isextension_is_initialized ? ("[" + isextension.toString() + "]")
						: "not initialized")
				+ ""
				+ "\n - BPM_PROCESSDEF_PROPERTY.CANINSTANTIATE = "
				+ (caninstantiate_is_initialized ? ("["
						+ caninstantiate.toString() + "]") : "not initialized")
				+ "";
	}

	// class+

	// class-
}

