apiVersion: ooder.io/v1
kind: SkillPackage

metadata:
  name: skill-vfs-minio
  version: 0.7.3
  description: MinIO存储服务 - 提供对象存储能力，支持S3兼容接口
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/ooder-skills/tree/main/skills/skill-vfs-minio
  repository: https://github.com/ooderCN/ooder-skills.git
  giteeMirror: https://gitee.com/ooderCN/ooder-skills.git
  keywords:
    - minio
    - vfs
    - storage
    - s3
    - object-storage

spec:
  type: enterprise-skill
  
  capabilities:
    - vfs-storage
    - file-read
    - file-write
    - file-delete
    - metadata

  scenes:
    - vfs-minio

  parameters:
    - name: MINIO_ENDPOINT
      type: string
      required: true
      description: MinIO服务端点
    - name: MINIO_ACCESS_KEY
      type: string
      required: true
      description: MinIO访问密钥
    - name: MINIO_SECRET_KEY
      type: string
      required: true
      secret: true
      description: MinIO秘密密钥
    - name: MINIO_BUCKET_NAME
      type: string
      required: true
      description: MinIO桶名称

  execution:
    timeout: 30000
    memoryLimit: 512M
    cpuLimit: 1

  distribution:
    format: jar
    entrypoint: net.ooder.skill.vfs.minio.MinioVfsApplication
    assets:
      - name: skill-vfs-minio-0.7.3.jar
        platform: all
        url: https://github.com/ooderCN/ooder-skills/releases/download/v0.7.3/skill-vfs-minio-0.7.3.jar
        giteeUrl: https://gitee.com/ooderCN/ooder-skills/releases/download/v0.7.3/skill-vfs-minio-0.7.3.jar

  compatibility:
    sdkVersion: ">=0.7.0"
    javaVersion: ">=8"