apiVersion: skill.ooder.net/v1
kind: Skill

metadata:
  id: skill-vfs-minio
  name: MinIO Storage Service
  version: 0.7.0
  description: MinIO object storage implementation with S3-compatible API
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/ooder-skills/tree/main/skills/skill-vfs-minio
  repository: https://github.com/ooderCN/ooder-skills.git
  keywords:
    - minio
    - s3
    - object-storage
    - vfs
    - self-hosted
  maintainers:
    - name: Ooder Team
      email: team@ooder.net
      github: ooderCN

spec:
  type: enterprise-skill
  
  runtime:
    language: java
    javaVersion: "8"
    framework: spring-boot
    mainClass: net.ooder.skill.vfs.minio.MinioVfsApplication
    jvmOpts: "-Xms256m -Xmx512m"
  
  vfsCapabilities:
    supported:
      - id: file-read
        name: File Read
        description: Read file content
        fallback: none
      - id: file-write
        name: File Write
        description: Write file content
        fallback: none
      - id: file-delete
        name: File Delete
        description: Delete file
        fallback: none
      - id: file-copy
        name: File Copy
        description: Copy file
        fallback: none
      - id: file-move
        name: File Move
        description: Move file
        fallback: none
      - id: folder-create
        name: Folder Create
        description: Create folder
        fallback: none
      - id: folder-list
        name: Folder List
        description: List folder contents
        fallback: none
      - id: file-share
        name: File Sharing
        description: Generate share links
        fallback: none
      - id: stream-upload
        name: Stream Upload
        description: Chunked upload large files
        fallback: none
      - id: stream-download
        name: Stream Download
        description: Stream download large files
        fallback: none
      - id: acl-manage
        name: ACL Management
        description: Access control list management
        fallback: none
      - id: metadata
        name: Metadata
        description: Custom metadata
        fallback: none
    notSupported:
      - id: file-version
        name: File Versioning
        description: File version management
        fallback: local-fallback
        fallbackDescription: Use local storage for versioning
      - id: file-preview
        name: File Preview
        description: Online preview
        fallback: none
        fallbackDescription: MinIO does not support preview
      - id: file-compress
        name: File Compression
        description: Compress/decompress files
        fallback: local-fallback
        fallbackDescription: Use local storage for compression
  
  config:
    required:
      - name: MINIO_ENDPOINT
        type: string
        description: MinIO endpoint (e.g., localhost:9000)
        secret: false
      - name: MINIO_ACCESS_KEY
        type: string
        description: Access Key
        secret: false
      - name: MINIO_SECRET_KEY
        type: string
        description: Secret Key
        secret: true
      - name: MINIO_BUCKET_NAME
        type: string
        description: Bucket name
        secret: false
    optional:
      - name: MINIO_SECURE
        type: boolean
        description: Use HTTPS
        default: false
        secret: false
      - name: MINIO_REGION
        type: string
        description: Region
        default: ""
        secret: false
  
  resources:
    cpu: "500m"
    memory: "512Mi"
    storage: "1Gi"
    network:
      ingress: true
      egress: true
      ports:
        - 8080
  
  deployment:
    modes:
      - remote-hosted
      - local-deployed
    singleton: true
    requiresAuth: true
    healthCheck:
      path: /actuator/health
      interval: 30
      timeout: 10
    startup:
      timeout: 60
      order: 10
