apiVersion: ooder.io/v1
kind: SkillPackage

metadata:
  name: skill-org-wecom
  version: 0.7.3
  description: 企业微信组织服务 - 提供企业微信组织架构同步和用户认证能力
  author: Ooder Team
  license: Apache-2.0
  homepage: https://github.com/ooderCN/ooder-skills/tree/main/skills/skill-org-wecom
  repository: https://github.com/ooderCN/ooder-skills.git
  giteeMirror: https://gitee.com/ooderCN/ooder-skills.git
  keywords:
    - wecom
    - enterprise-wechat
    - org
    - authentication
    - organization

spec:
  type: enterprise-skill
  
  capabilities:
    - org-data-read
    - org-data-sync
    - user-auth
    - department-query
    - user-query

  scenes:
    - auth

  parameters:
    - name: WECOM_CORP_ID
      type: string
      required: true
      description: 企业微信CorpId
    - name: WECOM_AGENT_ID
      type: string
      required: true
      description: 企业微信AgentId
    - name: WECOM_SECRET
      type: string
      required: true
      secret: true
      description: 企业微信Secret
    - name: WECOM_API_BASE_URL
      type: string
      required: false
      default: https://qyapi.weixin.qq.com
      description: 企业微信API基础URL
    - name: WECOM_TIMEOUT
      type: number
      required: false
      default: 30000
      description: 请求超时时间(毫秒)
    - name: WECOM_CACHE_ENABLED
      type: boolean
      required: false
      default: true
      description: 是否启用缓存
    - name: WECOM_CACHE_TTL
      type: number
      required: false
      default: 300000
      description: 缓存过期时间(毫秒)

  execution:
    timeout: 30000
    memoryLimit: 512M
    cpuLimit: 1

  distribution:
    format: jar
    entrypoint: net.ooder.skill.org.wecom.WeComOrgApplication
    assets:
      - name: skill-org-wecom-0.7.3.jar
        platform: all
        url: https://github.com/ooderCN/ooder-skills/releases/download/v0.7.3/skill-org-wecom-0.7.3.jar
        giteeUrl: https://gitee.com/ooderCN/ooder-skills/releases/download/v0.7.3/skill-org-wecom-0.7.3.jar

  compatibility:
    sdkVersion: ">=0.7.0"
    javaVersion: ">=8"