package net.ooder.skill.security.api;

import net.ooder.skill.security.dto.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Security API Test Cases
 * 
 * <p>Zero-configuration unit tests for SecurityApi implementation.</p>
 * 
 * @author Ooder Team
 * @version 2.3
 */
@DisplayName("Security API Tests")
class SecurityApiTest {

    private SecurityApi securityApi;

    @BeforeEach
    void setUp() {
        securityApi = new SecurityApiImpl();
        securityApi.initialize(new HashMap<>());
        securityApi.start();
    }

    @Nested
    @DisplayName("Lifecycle Tests")
    class LifecycleTests {

        @Test
        @DisplayName("Should initialize successfully")
        void shouldInitializeSuccessfully() {
            SecurityApi api = new SecurityApiImpl();
            assertFalse(api.isInitialized());
            
            api.initialize(new HashMap<>());
            assertTrue(api.isInitialized());
        }

        @Test
        @DisplayName("Should start and stop successfully")
        void shouldStartAndStopSuccessfully() {
            SecurityApi api = new SecurityApiImpl();
            api.initialize(new HashMap<>());
            
            assertFalse(api.isRunning());
            api.start();
            assertTrue(api.isRunning());
            
            api.stop();
            assertFalse(api.isRunning());
        }

        @Test
        @DisplayName("Should return correct API name and version")
        void shouldReturnCorrectApiNameAndVersion() {
            assertEquals("skill-security", securityApi.getApiName());
            assertEquals("2.3", securityApi.getVersion());
        }
    }

    @Nested
    @DisplayName("Policy Management Tests")
    class PolicyManagementTests {

        @Test
        @DisplayName("Should create policy with auto-generated ID")
        void shouldCreatePolicyWithAutoGeneratedId() {
            SecurityPolicy policy = new SecurityPolicy();
            policy.setPolicyName("Test Policy");
            policy.setPolicyType("access");
            
            SecurityPolicy created = securityApi.createPolicy(policy);
            
            assertNotNull(created.getPolicyId());
            assertEquals("Test Policy", created.getPolicyName());
            assertEquals("access", created.getPolicyType());
        }

        @Test
        @DisplayName("Should list all policies")
        void shouldListAllPolicies() {
            SecurityPolicy policy1 = new SecurityPolicy();
            policy1.setPolicyName("Policy 1");
            securityApi.createPolicy(policy1);
            
            SecurityPolicy policy2 = new SecurityPolicy();
            policy2.setPolicyName("Policy 2");
            securityApi.createPolicy(policy2);
            
            List<SecurityPolicy> policies = securityApi.listPolicies();
            
            assertEquals(2, policies.size());
        }

        @Test
        @DisplayName("Should get policy by ID")
        void shouldGetPolicyById() {
            SecurityPolicy policy = new SecurityPolicy();
            policy.setPolicyName("Test Policy");
            SecurityPolicy created = securityApi.createPolicy(policy);
            
            SecurityPolicy retrieved = securityApi.getPolicy(created.getPolicyId());
            
            assertNotNull(retrieved);
            assertEquals("Test Policy", retrieved.getPolicyName());
        }

        @Test
        @DisplayName("Should update policy")
        void shouldUpdatePolicy() {
            SecurityPolicy policy = new SecurityPolicy();
            policy.setPolicyName("Original Name");
            SecurityPolicy created = securityApi.createPolicy(policy);
            
            created.setPolicyName("Updated Name");
            SecurityPolicy updated = securityApi.updatePolicy(created.getPolicyId(), created);
            
            assertNotNull(updated);
            assertEquals("Updated Name", updated.getPolicyName());
        }

        @Test
        @DisplayName("Should delete policy")
        void shouldDeletePolicy() {
            SecurityPolicy policy = new SecurityPolicy();
            policy.setPolicyName("To Delete");
            SecurityPolicy created = securityApi.createPolicy(policy);
            
            assertTrue(securityApi.deletePolicy(created.getPolicyId()));
            assertNull(securityApi.getPolicy(created.getPolicyId()));
        }

        @Test
        @DisplayName("Should enable and disable policy")
        void shouldEnableAndDisablePolicy() {
            SecurityPolicy policy = new SecurityPolicy();
            policy.setPolicyName("Test Policy");
            SecurityPolicy created = securityApi.createPolicy(policy);
            
            assertTrue(securityApi.enablePolicy(created.getPolicyId()));
            assertTrue(securityApi.disablePolicy(created.getPolicyId()));
        }
    }

    @Nested
    @DisplayName("Access Control Tests")
    class AccessControlTests {

        @Test
        @DisplayName("Should create ACL entry")
        void shouldCreateAclEntry() {
            AccessControl acl = new AccessControl();
            acl.setUserId("user-001");
            acl.setResource("/api/data");
            acl.setAction("read");
            
            AccessControl created = securityApi.createAcl(acl);
            
            assertNotNull(created.getAclId());
            assertEquals("user-001", created.getUserId());
        }

        @Test
        @DisplayName("Should list all ACL entries")
        void shouldListAllAclEntries() {
            AccessControl acl1 = new AccessControl();
            acl1.setUserId("user-001");
            securityApi.createAcl(acl1);
            
            AccessControl acl2 = new AccessControl();
            acl2.setUserId("user-002");
            securityApi.createAcl(acl2);
            
            List<AccessControl> acls = securityApi.listAcls();
            
            assertEquals(2, acls.size());
        }

        @Test
        @DisplayName("Should delete ACL entry")
        void shouldDeleteAclEntry() {
            AccessControl acl = new AccessControl();
            acl.setUserId("user-001");
            AccessControl created = securityApi.createAcl(acl);
            
            assertTrue(securityApi.deleteAcl(created.getAclId()));
        }

        @Test
        @DisplayName("Should check permission")
        void shouldCheckPermission() {
            AccessControl acl = new AccessControl();
            acl.setUserId("user-001");
            acl.setResource("/api/data");
            acl.setAction("read");
            securityApi.createAcl(acl);
            
            boolean hasPermission = securityApi.checkPermission("user-001", "/api/data", "read");
            
            assertTrue(hasPermission);
        }
    }

    @Nested
    @DisplayName("Threat Management Tests")
    class ThreatManagementTests {

        @Test
        @DisplayName("Should report threat")
        void shouldReportThreat() {
            ThreatInfo threat = new ThreatInfo();
            threat.setType("intrusion");
            threat.setSeverity("high");
            threat.setSource("192.168.1.100");
            
            ThreatInfo reported = securityApi.reportThreat(threat);
            
            assertNotNull(reported.getThreatId());
            assertEquals("active", reported.getStatus());
            assertTrue(reported.getDetectedAt() > 0);
        }

        @Test
        @DisplayName("Should list threats by status")
        void shouldListThreatsByStatus() {
            ThreatInfo threat1 = new ThreatInfo();
            threat1.setType("malware");
            securityApi.reportThreat(threat1);
            
            ThreatInfo threat2 = new ThreatInfo();
            threat2.setType("intrusion");
            ThreatInfo reported = securityApi.reportThreat(threat2);
            securityApi.resolveThreat(reported.getThreatId(), "Fixed");
            
            List<ThreatInfo> activeThreats = securityApi.listThreats("active");
            List<ThreatInfo> resolvedThreats = securityApi.listThreats("resolved");
            
            assertEquals(1, activeThreats.size());
            assertEquals(1, resolvedThreats.size());
        }

        @Test
        @DisplayName("Should resolve threat")
        void shouldResolveThreat() {
            ThreatInfo threat = new ThreatInfo();
            threat.setType("ddos");
            ThreatInfo reported = securityApi.reportThreat(threat);
            
            ThreatInfo resolved = securityApi.resolveThreat(reported.getThreatId(), "Blocked IP");
            
            assertEquals("resolved", resolved.getStatus());
            assertEquals("Blocked IP", resolved.getResolution());
            assertTrue(resolved.getResolvedAt() > 0);
        }
    }

    @Nested
    @DisplayName("Firewall Tests")
    class FirewallTests {

        @Test
        @DisplayName("Should enable and disable firewall")
        void shouldEnableAndDisableFirewall() {
            assertTrue(securityApi.enableFirewall());
            assertTrue(securityApi.getFirewallStatus().isEnabled());
            
            assertTrue(securityApi.disableFirewall());
            assertFalse(securityApi.getFirewallStatus().isEnabled());
        }

        @Test
        @DisplayName("Should add firewall rule")
        void shouldAddFirewallRule() {
            FirewallRule rule = new FirewallRule();
            rule.setName("Block Malicious IP");
            rule.setAction("deny");
            rule.setProtocol("tcp");
            rule.setSourceIp("10.0.0.0/8");
            
            FirewallRule added = securityApi.addFirewallRule(rule);
            
            assertNotNull(added.getRuleId());
            assertEquals(1, securityApi.listFirewallRules().size());
        }

        @Test
        @DisplayName("Should remove firewall rule")
        void shouldRemoveFirewallRule() {
            FirewallRule rule = new FirewallRule();
            rule.setName("Test Rule");
            FirewallRule added = securityApi.addFirewallRule(rule);
            
            assertTrue(securityApi.removeFirewallRule(added.getRuleId()));
            assertEquals(0, securityApi.listFirewallRules().size());
        }

        @Test
        @DisplayName("Should get firewall status")
        void shouldGetFirewallStatus() {
            securityApi.enableFirewall();
            securityApi.addFirewallRule(new FirewallRule());
            
            FirewallStatus status = securityApi.getFirewallStatus();
            
            assertTrue(status.isEnabled());
            assertEquals(1, status.getActiveRules());
        }
    }

    @Nested
    @DisplayName("Status and Statistics Tests")
    class StatusAndStatisticsTests {

        @Test
        @DisplayName("Should get security status")
        void shouldGetSecurityStatus() {
            SecurityStatus status = securityApi.getStatus();
            
            assertNotNull(status);
            assertEquals("SECURE", status.getStatus());
            assertTrue(status.isFirewallEnabled());
        }

        @Test
        @DisplayName("Should get security statistics")
        void shouldGetSecurityStatistics() {
            securityApi.createPolicy(new SecurityPolicy());
            securityApi.createAcl(new AccessControl());
            securityApi.reportThreat(new ThreatInfo());
            
            SecurityStats stats = securityApi.getStats();
            
            assertNotNull(stats);
            assertEquals(1, stats.getTotalPolicies());
            assertEquals(1, stats.getTotalAcls());
            assertEquals(1, stats.getTotalThreats());
        }

        @Test
        @DisplayName("Should query audit logs")
        void shouldQueryAuditLogs() {
            Map<String, Object> query = new HashMap<>();
            query.put("userId", "user-001");
            
            List<AuditLog> logs = securityApi.queryAuditLogs(query);
            
            assertNotNull(logs);
        }

        @Test
        @DisplayName("Should get audit statistics")
        void shouldGetAuditStatistics() {
            AuditStats stats = securityApi.getAuditStats();
            
            assertNotNull(stats);
            assertTrue(stats.getTotalLogs() >= 0);
        }
    }
}
